#- "./data:/usr/share/elasticsearch/data"
version: '2.2'
services:

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3"
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - docker_elk

  logstash:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3"
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch      

  kibana:
    image: "docker.elastic.co/kibana/kibana:6.2.2"
    container_name: kibana
    links:
      - elasticsearch
    ports:
      - "5601:5601"
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    networks:
      - docker_elk

networks:
  docker_elk:
    driver: bridge
